### ISSUE TITLE
Banner takes up a lot of space on mobile

### ISSUE THREAD

**Issue by jaspervdj** [chshersh/chshersh.github.io#19]
Screenshot:

![image](https://user-images.githubusercontent.com/95501/54925324-a4080100-4f40-11e9-9fd2-7a3e8dd60f3e.png)

**Comment by chshersh** [comment]
@jaspervdj Thanks for reporting! I'm not a frontend person and didn't test thoroughly on mobile devices. But I will try to look into this to see what can be done.

**Comment by chshersh** [comment]
@jaspervdj I deployed newer version. Should be fixed now :+1:

**Comment by jaspervdj** [comment]
Thanks, much nicer to read!
