### ISSUE TITLE
Generate footer automatically for articles

### ISSUE THREAD

**Issue by chshersh** [chshersh/chshersh.github.io#94]
Should include:

- X link
- YouTube link
- Twitch link
- BlueSky link
- Sponsorship link

**Comment by softinio** [comment]
Be nice to have a mastodon link too. Thanks 🙏

**Comment by chshersh** [comment]
@softinio Good idea! 😅 

But I'm not really active on Mastodon, so I don't give a false impression that it makes sense to follow me there or expect interactions from there.

But I probably can start sharing my posts there when I write them, why not.

**Comment by softinio** [comment]
Thanks for liking my suggestion :) 

I think Mastodon is worth the trouble  :) 

There are some hidden features that are really nice too, like I can follow your posts using my rss reader if I want by just adding `.rss` to the end of your mastodon profile url, ie [https://functional.cafe/@chshersh.rss](https://functional.cafe/@chshersh.rss). 

Keep in touch.

ps: Your new blog looks great! I need to write more on mine :)

**Comment by chshersh** [comment]
This was done in https://github.com/chshersh/chshersh.github.io/commit/55f6514ee1cfd76b8199cb0fa7cd9681b2ab990b

The changes were deployed but it might take up to 30 minutes to update the cache (or you can force reload the page).

![image](https://github.com/user-attachments/assets/75b73ebf-34c3-49b2-9096-e48a4faf6777)
