### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by mitchpaulus** [chshersh/chshersh.github.io#96]
I enjoyed reading your articles, and I used to have a link to an RSS feed at <https://chshersh.com/rss.xml>. However, it looks like there was a redesign, and that link is no longer valid. I didn't find a new link. Consider this to be a gentle nudge to bring that back, hopefully, to the same URL in case there were others. Thanks!

**Comment by chshersh** [comment]
Hi @mitchpaulus,

Indeed, there was a full rewrite of the website and this link was lost in the process.

I see what I can do to bring it back.

**Comment by chshersh** [comment]
This is fixed now. My blog now has Atom and RSS feeds:

- https://chshersh.com/atom.xml
- https://chshersh.com/rss.xml

I've run online validation tools and both seem fine. Let me know if you experience any issues!
